//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityDataLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string ConfigName { get; set; }
        public string ConfigValue { get; set; }
        public string DataType { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
