//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityDataLayer.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdentityDBEntities : DbContext
    {
        public IdentityDBEntities()
            : base("name=IdentityDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<Finger> Fingers { get; set; }
        public virtual DbSet<GenericPerson> GenericPersons { get; set; }
        public virtual DbSet<PersonPicture> PersonPictures { get; set; }
        public virtual DbSet<StaffPerson> StaffPersons { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<PersonFinger> PersonFingers { get; set; }
        public virtual DbSet<IDSnapshot> IDSnapshots { get; set; }
        public virtual DbSet<College> Colleges { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<StudentPerson> StudentPersons { get; set; }
        public virtual DbSet<StudentCategory> StudentCategories { get; set; }
    }
}
