//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityDataLayer.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPerson
    {
        public int PersonId { get; set; }
        public string EntrySession { get; set; }
        public int CurrentDepartmentId { get; set; }
        public string CurrentLevel { get; set; }
        public string SponsorName { get; set; }
        public string SponsorPhone { get; set; }
        public string SponsorAddress { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string LastEnrollmentSession { get; set; }
        public string LastEnrollmentStatus { get; set; }
        public int StudentCategoryId { get; set; }
        public string Program { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Person Person { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual StudentCategory StudentCategory { get; set; }
    }
}
