//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroup
    {
        public string BloodGroup1 { get; set; }
    }
}
