//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string IdentityNo { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Address { get; set; }
        public string HealthCentreNo { get; set; }
        public string Sex { get; set; }
        public string BloodGroup { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte[] CurrentPhoto { get; set; }
        public byte[] AuthorizedSignature { get; set; }
        public Nullable<int> CurrentSnapshotId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public int IDCardPrintCount { get; set; }
        public Nullable<System.DateTime> DateLastPrinted { get; set; }
        public byte[] WatermarkedPhoto { get; set; }
    
        public virtual GenericPerson GenericPerson { get; set; }
        public virtual IDCardPrintCount IDCardPrintCount1 { get; set; }
        public virtual StaffPerson StaffPerson { get; set; }
        public virtual StudentPerson StudentPerson { get; set; }
    }
}
