//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityBusinessLayer.PortalServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentRecord", Namespace="http://schemas.datacontract.org/2004/07/StudentPortal.WebServices")]
    [System.SerializableAttribute()]
    public partial class StudentRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CGPAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollegeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatricNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddlenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgrammeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UTMENoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CGPA {
            get {
                return this.CGPAField;
            }
            set {
                if ((object.ReferenceEquals(this.CGPAField, value) != true)) {
                    this.CGPAField = value;
                    this.RaisePropertyChanged("CGPA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string College {
            get {
                return this.CollegeField;
            }
            set {
                if ((object.ReferenceEquals(this.CollegeField, value) != true)) {
                    this.CollegeField = value;
                    this.RaisePropertyChanged("College");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatricNo {
            get {
                return this.MatricNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MatricNoField, value) != true)) {
                    this.MatricNoField = value;
                    this.RaisePropertyChanged("MatricNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Middlename {
            get {
                return this.MiddlenameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddlenameField, value) != true)) {
                    this.MiddlenameField = value;
                    this.RaisePropertyChanged("Middlename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinDuration {
            get {
                return this.MinDurationField;
            }
            set {
                if ((object.ReferenceEquals(this.MinDurationField, value) != true)) {
                    this.MinDurationField = value;
                    this.RaisePropertyChanged("MinDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatus {
            get {
                return this.PaymentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentStatusField, value) != true)) {
                    this.PaymentStatusField = value;
                    this.RaisePropertyChanged("PaymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileUrl {
            get {
                return this.ProfileUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileUrlField, value) != true)) {
                    this.ProfileUrlField = value;
                    this.RaisePropertyChanged("ProfileUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Programme {
            get {
                return this.ProgrammeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgrammeField, value) != true)) {
                    this.ProgrammeField = value;
                    this.RaisePropertyChanged("Programme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorAddress {
            get {
                return this.SponsorAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorAddressField, value) != true)) {
                    this.SponsorAddressField = value;
                    this.RaisePropertyChanged("SponsorAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorName {
            get {
                return this.SponsorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorNameField, value) != true)) {
                    this.SponsorNameField = value;
                    this.RaisePropertyChanged("SponsorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorPhone {
            get {
                return this.SponsorPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorPhoneField, value) != true)) {
                    this.SponsorPhoneField = value;
                    this.RaisePropertyChanged("SponsorPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UTMENo {
            get {
                return this.UTMENoField;
            }
            set {
                if ((object.ReferenceEquals(this.UTMENoField, value) != true)) {
                    this.UTMENoField = value;
                    this.RaisePropertyChanged("UTMENo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PortalServ.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/getStudentRecord", ReplyAction="http://tempuri.org/IProfileService/getStudentRecordResponse")]
        IdentityBusinessLayer.PortalServ.StudentRecord getStudentRecord(string MatricNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/getStudentRecord", ReplyAction="http://tempuri.org/IProfileService/getStudentRecordResponse")]
        System.Threading.Tasks.Task<IdentityBusinessLayer.PortalServ.StudentRecord> getStudentRecordAsync(string MatricNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/getStudentRecordWithSession", ReplyAction="http://tempuri.org/IProfileService/getStudentRecordWithSessionResponse")]
        IdentityBusinessLayer.PortalServ.StudentRecord getStudentRecordWithSession(string MatricNo, string Session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/getStudentRecordWithSession", ReplyAction="http://tempuri.org/IProfileService/getStudentRecordWithSessionResponse")]
        System.Threading.Tasks.Task<IdentityBusinessLayer.PortalServ.StudentRecord> getStudentRecordWithSessionAsync(string MatricNo, string Session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updateProfile", ReplyAction="http://tempuri.org/IProfileService/updateProfileResponse")]
        string updateProfile(string MatricNo, string email, string email2, string phone, string phone2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updateProfile", ReplyAction="http://tempuri.org/IProfileService/updateProfileResponse")]
        System.Threading.Tasks.Task<string> updateProfileAsync(string MatricNo, string email, string email2, string phone, string phone2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/openProfile", ReplyAction="http://tempuri.org/IProfileService/openProfileResponse")]
        string openProfile(string MatricNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/openProfile", ReplyAction="http://tempuri.org/IProfileService/openProfileResponse")]
        System.Threading.Tasks.Task<string> openProfileAsync(string MatricNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/openCourseForm", ReplyAction="http://tempuri.org/IProfileService/openCourseFormResponse")]
        string openCourseForm(string MatricNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/openCourseForm", ReplyAction="http://tempuri.org/IProfileService/openCourseFormResponse")]
        System.Threading.Tasks.Task<string> openCourseFormAsync(string MatricNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : IdentityBusinessLayer.PortalServ.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<IdentityBusinessLayer.PortalServ.IProfileService>, IdentityBusinessLayer.PortalServ.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IdentityBusinessLayer.PortalServ.StudentRecord getStudentRecord(string MatricNo) {
            return base.Channel.getStudentRecord(MatricNo);
        }
        
        public System.Threading.Tasks.Task<IdentityBusinessLayer.PortalServ.StudentRecord> getStudentRecordAsync(string MatricNo) {
            return base.Channel.getStudentRecordAsync(MatricNo);
        }
        
        public IdentityBusinessLayer.PortalServ.StudentRecord getStudentRecordWithSession(string MatricNo, string Session) {
            return base.Channel.getStudentRecordWithSession(MatricNo, Session);
        }
        
        public System.Threading.Tasks.Task<IdentityBusinessLayer.PortalServ.StudentRecord> getStudentRecordWithSessionAsync(string MatricNo, string Session) {
            return base.Channel.getStudentRecordWithSessionAsync(MatricNo, Session);
        }
        
        public string updateProfile(string MatricNo, string email, string email2, string phone, string phone2) {
            return base.Channel.updateProfile(MatricNo, email, email2, phone, phone2);
        }
        
        public System.Threading.Tasks.Task<string> updateProfileAsync(string MatricNo, string email, string email2, string phone, string phone2) {
            return base.Channel.updateProfileAsync(MatricNo, email, email2, phone, phone2);
        }
        
        public string openProfile(string MatricNo) {
            return base.Channel.openProfile(MatricNo);
        }
        
        public System.Threading.Tasks.Task<string> openProfileAsync(string MatricNo) {
            return base.Channel.openProfileAsync(MatricNo);
        }
        
        public string openCourseForm(string MatricNo) {
            return base.Channel.openCourseForm(MatricNo);
        }
        
        public System.Threading.Tasks.Task<string> openCourseFormAsync(string MatricNo) {
            return base.Channel.openCourseFormAsync(MatricNo);
        }
    }
}
